# Generated by Django 4.2.1 on 2023-05-25 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutranta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_calroes', models.IntegerField(default=0)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nutranta_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutranta_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Kot Begum', 'Kot Begum'), ('Thokar Naiz baig', 'Thokar Naiz baig'), ('Shah Alam Market', 'Shah Alam Market'), ('Model Town', 'Model Town'), ('wapda Town', 'wapda Town'), ('Gulshan Ravi', 'Gulshan Ravi'), ('Gulberg', 'Gulberg'), ('Garden Town', 'Garden Town'), ('Faisal Town', 'Faisal Town'), ('DHA', 'DHA'), ('Cantt', 'Cantt'), ('Johar Town', 'Johar Town'), ('Bahria Town', 'Bahria Town'), ('Askari', 'Askari'), ('Valencia', 'Valencia'), ('Punjab Society', 'Punjab Society'), ('Punjab Coop Housing Society', 'Punjab Coop Housing Society'), ('Punjab Govt Servants Housing Foundation', 'Punjab Govt Servants Housing Foundation'), ('Punjab Small Industries Colony', 'Punjab Small Industries Colony'), ('Punjab University Employees Society', 'Punjab University Employees Society'), ('Punjab University Society', 'Punjab University Society'), ('Punjab Govt Employees Society', 'Punjab Govt Employees Society')], max_length=50)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nutranta_app.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
