# Generated by Django 4.2.1 on 2023-05-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutranta_app', '0002_orderplaced_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_iron',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_magnesium',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_vitamin_a',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_vitamin_c',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_water',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_zinc',
        ),
        migrations.AlterField(
            model_name='product',
            name='total_calcium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_calroes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_vitamin_d',
            field=models.FloatField(default=0),
        ),
    ]
