# Generated by Django 4.2.1 on 2023-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutranta_app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'vegetables'), ('fruits', 'fruits'), ('dairy', 'dairy'), ('fish', 'fish')], max_length=50),
        ),
    ]
