# Generated by Django 4.2.1 on 2023-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutranta_app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('v', 'vegetables'), ('f', 'fruits'), ('d', 'dairy'), ('fi', 'fish')], max_length=50),
        ),
    ]
