# Generated by Django 4.2.1 on 2023-05-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutranta_app', '0008_customer_email_customer_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_calroes',
        ),
    ]
