# Generated by Django 4.2.1 on 2023-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutranta_app', '0009_remove_cart_total_calroes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
